/* eslint-disable no-unused-vars */

export enum PHASES {
  INTRO,
  GET_DETAILS,
  PILE_INSTRUCTIONS,
  TRANSITION_HELPER,
  HELPER_INSTRUCTIONS,
  PHASE_ONE_BLINDING,
  TRANSITION_EXPERIMENTER,
  EXPERIMENTER_INSTRUCTIONS,
  PHASE_TWO_BLINDING,
  FILE_DOWNLOAD,
  OUTRO,
}

export enum PILL {
  CONTROL = 'Control',
  TREATMENT = 'Treatment',
}
